apiVersion: v1
kind: Namespace
metadata:
  name: github
  labels:
    app.kubernetes.io/name: github
    app.kubernetes.io/instance: github
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  github-runner
  namespace: github
  labels:
    app.kubernetes.io/name:  github-runner
  replicas: 1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  github-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  github-runner
    spec:
      containers:
        - name:  github-runner
          image: {{ .Values.image.url }}:{{ .Values.images.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          env:
            - name: AUTH_PAT
              value: {{ .Values.github.pat }}
            - name: GITHUB_ORGANIZATION
              value: {{ .Values.github.organization }}

